project:
  type: website
  pre-render:
  - R/download_data.R  # download field data from Google Sheets
  render:
  - index.qmd

website:
  title: "Mangrove Structure in Placencia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://github.com/USF-IMaRS/mangrove-structure-in-placencia
        text: Source Code
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    message: false
    warning: false


